services:
  autosync:
    image: casfergroup/autosync:latest
    environment:
      - ENABLE_CRON=true
      - S3_REMOTE=myremote
      - S3_PATH=mybucket/backups
    volumes:
      - ./rclone.conf:/root/.config/rclone/rclone.conf:ro # Rclone config file
      - /media/your_data:/data/ # Data synchronization mount point"
    restart: unless-stopped