name: Push to Docker Hub
permissions:
  contents: read
  security-events: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'build/**'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and export locally (for SAST scan)
        uses: docker/build-push-action@v6
        with:
          context: ./build
          tags: autosync-test
          load: true
          platforms: linux/amd64

      - name: Save image to tar file
        run: docker save autosync-test -o image.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: autosync-test
          path: image.tar

  sast:
    runs-on: ubuntu-latest
    needs: test-build
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: autosync-test

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: 'autosync-test'
          format: 'sarif'
          exit-code: '0' # Won't fail on vulns found
          ignore-unfixed: true # Won't flag if there isn't a fix to the CVE
          output: 'trivy-results.sarif'

      - name: Upload Trivy SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  sbom:
    runs-on: ubuntu-latest
    needs: test-build
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: autosync-test

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: 'image'
          image-ref: 'autosync-test'
          format: 'github'
          output: 'dependency-results.sbom.json'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set BUILD_DATE
        run: echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          # list of Docker images to use as base name for tags
          images: |
            casfergroup/autosync           
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ env.BUILD_DATE }}
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./build
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
