name: PR Tests
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      - 'build/**'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and export locally (for SAST scan)
        uses: docker/build-push-action@v6
        with:
          context: ./build
          tags: casfergroup/autosync:test
          load: true 
          platforms: linux/amd64

      - name: Save image to tar file
        run: docker save casfergroup/autosync:test -o autosync.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: autosync-image
          path: autosync.tar

  sast:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: autosync-image

      - name: Load Docker image
        run: docker load -i autosync.tar

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.31.0
        with:
              image-ref: 'casfergroup/autosync:test'
              format: 'table'
              severity: 'CRITICAL,HIGH,MEDIUM'
              exit-code: '1'