name: Weekly SAST
permissions:
  security-events: write

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy scan on the latest image
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'casfergroup/autosync:latest'
          format: 'sarif'
          severity: 'MEDIUM,HIGH,CRITICAL'
          exit-code: '1'
          output: 'trivy-results.sarif'

      - name: Upload rebuild Trivy SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'